// flow-typed signature: c92c71189c2e759e761c3a7175d1d108
// flow-typed version: <<STUB>>/sass-variable-loader_v^0.1.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-variable-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-variable-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass-variable-loader/dist/get-variables' {
  declare module.exports: any;
}

declare module 'sass-variable-loader/dist/index' {
  declare module.exports: any;
}

declare module 'sass-variable-loader/dist/parse-variables' {
  declare module.exports: any;
}

declare module 'sass-variable-loader/src/get-variables' {
  declare module.exports: any;
}

declare module 'sass-variable-loader/src/index' {
  declare module.exports: any;
}

declare module 'sass-variable-loader/src/parse-variables' {
  declare module.exports: any;
}

declare module 'sass-variable-loader/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sass-variable-loader/dist/get-variables.js' {
  declare module.exports: $Exports<'sass-variable-loader/dist/get-variables'>;
}
declare module 'sass-variable-loader/dist/index.js' {
  declare module.exports: $Exports<'sass-variable-loader/dist/index'>;
}
declare module 'sass-variable-loader/dist/parse-variables.js' {
  declare module.exports: $Exports<'sass-variable-loader/dist/parse-variables'>;
}
declare module 'sass-variable-loader/src/get-variables.js' {
  declare module.exports: $Exports<'sass-variable-loader/src/get-variables'>;
}
declare module 'sass-variable-loader/src/index.js' {
  declare module.exports: $Exports<'sass-variable-loader/src/index'>;
}
declare module 'sass-variable-loader/src/parse-variables.js' {
  declare module.exports: $Exports<'sass-variable-loader/src/parse-variables'>;
}
declare module 'sass-variable-loader/test/index.test.js' {
  declare module.exports: $Exports<'sass-variable-loader/test/index.test'>;
}
